### ISSUE TITLE
[BUG] Interfaces in separate files not found due to file encoding (ANSI vs UTF-8)

### ISSUE THREAD

**Issue by kajnelissen** [compodoc/compodoc#244] opened 2017-07-25 10:23 UTC
##### **Overview of the issue**

I have an interface located in a separate file `ICustomAction.ts` which looks this like this:

```typescript
export interface ICustomAction {
    Kind: string;
    CustomProperty: string;
}
```

In the build output I can see that Compodoc parsed the file, but did not find anything in it. The file encoding is UTF-8. When I change to encoding to ANSI, it actually finds the interface after parsing the file. This only seems to happen with interfaces. I tried the same encoding switch for files with components, but UTF-8 as well as ANSI were parsed and ended up in the docs. Also generated a clean Angular project using the CLI, pasted the interface in that project, build the docs and got the same result.

##### **Operating System, Node.js, npm, compodoc version(s)**

* **OS:** Windows 10
* **Node:** version 6.10.2
* **NPM:** version 4.4.4
* **Compodoc:** version 1.0.0-beta.13

##### **Angular configuration, a `package.json` file in the root folder**

See command below.

##### **Compodoc installed globally or locally ?**

_Locally_. Command in package.json looks like this: `"docs:build": "compodoc -p tsconfig.json --disableSourceCode --disablePrivateOrInternalSupport --disableGraph --hideGenerator --includes ./docs/files --theme readthedocs --includesName \"General\" -d ./generated-docs -y ./docs/styles -a ./docs/assets"`

##### **Motivation for or Use Case**

Most files are encoded as UTF-8 by default nowadays due to the advantages it has over ANSI. People might get confused when they see their interface is parsed, but not found.

##### **Reproduce the error**

* Copy the interface from the example into a file called `ICustomAction.ts` and save it with UTF-8 as encoding scheme.
* Build the docs and the output will say that the file was parsed, but nothing was found however.

**Comment by kajnelissen** [comment] 2017-07-25 11:00
Same thing for comments. Have the following property in a service:

```typescript
/**
 * Emits an event every time a scroll is detected.
 */
public scrollEvent: EventEmitter<any> = new EventEmitter();
```

When encoded in UTF-8, the comment is not visible in the documentation, with ANSI it is.

**Comment by vogloblinsky** [comment] 2017-07-28 06:40
@kajnelissen 
Could not reproduce it.
Just tested on a Windows 10 VM, with your Node.js version, on https://github.com/compodoc/compodoc-demo-todomvc-angular demo project.
Could you please send me a light Angular-cli generated project with your file not being parsed ?
Thanks

**Comment by kajnelissen** [comment] 2017-07-31 12:29
Check [this repository](https://github.com/kajnelissen/compodoc-interface-issue) for an example. The issue is with the `CustomPropertyService` and `CustomPropertyServiceInterface` which are both located in `src/app/service`.

The generated docs in the `generated-docs-ansi` folder were generated with both files being encoded as ANSI, while the docs in `generated-docs-utf8` were generated with encoding UTF-8.

**Comment by vogloblinsky** [comment] 2017-07-31 20:52
Ok reproduced with your example repository.
This has been fixed one week and an half ago, with this commit : https://github.com/compodoc/compodoc/commit/3f4707cb03ec6ffcdba0438effbc0f4efaef6e71

It will come in next release 1.0.0-beta.14 very soon.

You can test the development version if you want : 

```
npm i --save-dev https://github.com/compodoc/compodoc#develop
node_modules/bin/compodoc -p src/tsconfig.json
```

**Comment by vogloblinsky** [comment] 2017-08-11 06:24
I close this issue, 1.0.0-beta.14 released.

**Closed by vogloblinsky** 2017-08-11 06:24 UTC
Labels: Status: Completed, Status: Waiting feedback, Time: ~1 hour, Type: Bug
