### ISSUE TITLE
[BUG]] Err when npm run doc:buildandserve

### ISSUE THREAD

**Issue by badbytes1** [compodoc/compodoc#444] opened 2018-01-23 09:39 UTC
##### **Overview of the issue**

After Follow the Tutorial the command npm run doc:buildandserve generate an error

##### **Operating System, Node.js, npm, compodoc version(s)**

Win 10, v8.9.4, 5.6,latest

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "egret",
  "version": "5.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "doc:build": "compodoc -p src/tsconfig.app.json",
    "doc:serve": "compodoc -s",
    "doc:buildandserve": "compodoc -p src/tsconfig.app.json -s",
    "start": "ng serve",
    "serveProd": "ng serve --environment=prod",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "5.1.0",
    "@angular/cdk": "5.0.0",
    "@angular/common": "5.1.0",
    "@angular/compiler": "5.1.0",
    "@angular/core": "5.1.0",
    "@angular/flex-layout": "2.0.0-beta.10",
    "@angular/forms": "5.1.0",
    "@angular/http": "5.1.0",
    "@angular/material": "5.0.0",
    "@angular/platform-browser": "5.1.0",
    "@angular/platform-browser-dynamic": "5.1.0",
    "@angular/router": "5.1.0",
    "@swimlane/ngx-datatable": "11.0.0",
    "angular-calendar": "0.21.3",
    "chart.js": "2.5.0",
    "classlist.js": "1.1.20150312",
    "core-js": "2.4.1",
    "date-fns": "1.28.5",
    "hammerjs": "2.0.8",
    "hopscotch": "0.3.1",
    "ng2-charts": "1.6.0",
    "ng2-dragula": "1.3.1",
    "ng2-file-upload": "1.2.1",
    "ng2-translate": "5.0.0",
    "ng2-validation": "4.2.0",
    "ngx-quill": "2.0.4",
    "npm-install-peers": "^1.2.1",
    "perfect-scrollbar": "0.7.1",
    "rxjs": "5.5.2",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular-devkit/core": "0.0.28",
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "5.1.0",
    "@compodoc/compodoc": "^1.0.5",
    "@types/hopscotch": "0.2.28",
    "@types/jasmine": "2.5.38",
    "@types/node": "6.0.60",
    "codelyzer": "~2.0.0",
    "enhanced-resolve": "3.3.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "~0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "2.0.0",
    "tslint": "4.5.0",
    "typescript": "2.4.2"
  }
}

##### **Compodoc installed globally or locally ?**

globally and tried locally

##### **Motivation for or Use Case**

i can'acces to the doc.

##### **Reproduce the error**

When i run npm run doc:buildandserve i have this error:
![image](https://user-images.githubusercontent.com/31258986/35268515-a0f7e118-0029-11e8-93a9-4f223a6d6f7b.png)

**Comment by vogloblinsky** [comment] 2018-01-23 10:08
Duplicate of #326

**Closed** 2018-01-23 16:39 UTC
Labels: 1. Type: Bug, 1. Type: Duplicate, Status: Completed
