### ISSUE TITLE
[BUG] : Error during graph generation

### ISSUE THREAD

**Issue by emolr** [compodoc/compodoc#23] opened 2016-11-17 18:54 UTC
```
Error during graph generation: : /bin/sh: /usr/local/lib/node_modules/.bin/ngd: No such file or directory
```

I just did `npm i -g compodoc` && compodoc -p src/tsconfig.json -s

I can't seem to figure out what ngd is about. 

I can serve the documentation (it's really nice! ), only thing is that is says "your browser does not support svg", which it does, so it might be related.

**Comment by vogloblinsky** [comment] 2016-11-17 19:10
What is your environment ?
OS ? node/npm version ?

**Comment by vogloblinsky** [comment] 2016-11-29 14:05
@emolr 
What is your environment ?
OS ? node/npm version ?

**Comment by johanbenschop** [comment] 2016-11-30 09:13
I have the same issue. Running Windows 10 (1607), NodeJs v6.4.0 and NPM 3.10.3. I installed compodoc by listing it as a dev dependency and using yarn (v0.15.1) to fetch it.

```
[10:04:43] Copy main resources
[10:04:43] Process main graph
[10:04:43] Error during graph generation: : 'C:\Dev\Repos\my-project\src\Just.A.Namespace\node_modules\.bin\ngd' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by vogloblinsky** [comment] 2016-11-30 09:20
@johanbenschop can i have a screenshot of your node_modules\.bin folder ?

**Comment by johanbenschop** [comment] 2016-11-30 09:30
I'll do a pastebin instead: http://pastebin.com/C4hiL2TZ.

**Comment by vogloblinsky** [comment] 2016-11-30 09:33
And your package.json please ?

It seems that ngd is not installed during compodoc installation.

**Comment by johanbenschop** [comment] 2016-11-30 09:40
The package.json: http://pastebin.com/Gjaswu56

**Comment by vogloblinsky** [comment] 2016-11-30 09:47
Thanks, did you confirm this scenario for the test case ?
install node 6.4.0
install yarn 0.15.1
use package.json file in an empty folder
> yarn

**Comment by johanbenschop** [comment] 2016-11-30 09:59
Now it works with a node_modules with NPM. Removed the yarn.lock and tried it with that, no ngd again, so this seems to be a yarn issue. Thanks for your time!

**Comment by vogloblinsky** [comment] 2016-11-30 10:02
Ok fine.
I will test your configuration later. I am downloading a modern.ie Windows 10 virtual machine for testing.
The tests are just running with npm, but while Travis now supports Yarn, i will add a test case with it too.

**Comment by johanbenschop** [comment] 2016-11-30 10:08
The related GitHub issue from the yarn project about this: https://github.com/yarnpkg/yarn/issues/760. It looks like they fixed it and later reverted the fix for some reason.

**Comment by vogloblinsky** [comment] 2016-12-05 15:57
@johanbenschop Yarn 0.18.0 just released (https://github.com/yarnpkg/yarn/releases/tag/v0.18.0), bug #760 seems closed, could you test on your side ?
Thanks

**Comment by vogloblinsky** [comment] 2016-12-11 06:20
After testing 0.18.0 and last nightly-build, the bug is still present in yarn...

**Comment by IckleChris** [comment] 2016-12-13 22:28
I'm getting the same issue here, not using Yarn.

Mac OS 10.11.3 (El Capitan)
NPM version 3.10.9
Node version 7.2.1

Let me know if I can help in some way!

**Comment by vogloblinsky** [comment] 2016-12-14 01:13
@IckleChris : for what kind of project ? an angular-cli one ?

**Comment by IckleChris** [comment] 2016-12-14 08:06
Yes angular-cli. When I get the chance today I'll try with a fresh project.

**Comment by vogloblinsky** [comment] 2016-12-14 09:07
ok can i have your angular-cli version ?
compodoc installed in global ?

**Comment by IckleChris** [comment] 2016-12-14 09:12
I've just tried installing compodoc locally within the project and that works fine. Issue only appears to happen when installed globally.

angular-cli version is `1.0.0-beta.22-1`

**Comment by vogloblinsky** [comment] 2016-12-16 05:40
@IckleChris 
Cannot reproduce your bug.
On a fresh Mac OSX El Capitan : 
- installed Node.js 7.2.1
- installed npm 3.10.9
- installed compodoc in global : npm i -g compodoc
- cloned demo repo : https://github.com/compodoc/compodoc-demo-todomvc-angular2
- launch compodoc -p src/tsconfig.json -s and it works fine

- which compodoc gives me : /usr/local/bin/compodoc
- compodoc is located here : /usr/local/lib/node_modules/compodoc
- ng is located here : /usr/local/lib/node_modules/compodoc/node_modules/angular2-dependencies-graph

**Comment by flashdave1973** [comment] 2017-01-02 01:37
this may be [related to ](https://github.com/compodoc/compodoc/issues/43)does any of your code contain double forward slasheds for commented code?

**Comment by vogloblinsky** [comment] 2017-02-18 00:39
Closing, last version use ngd directly without CLI call as before. Give it a try ;)

**Closed by vogloblinsky** 2017-02-18 00:39 UTC
Labels: bug, yarn-bug
