### ISSUE TITLE
[BUG] Warning: no hard-coded metrics for 'sans-serif'.

### ISSUE THREAD

**Issue by rgant** [compodoc/compodoc#1285] opened 2022-08-17 13:59 UTC
##### **Overview of the issue**

I get these warnings when building the docs:
```
> npx compodoc --tsconfig tsconfig.json --silent

Compodoc v1.1.19
Warning: no hard-coded metrics for 'sans-serif'.  Falling back to 'Times' metrics
Warning: no hard-coded metrics for 'sans-serif'.  Falling back to 'Times' metrics
Warning: no hard-coded metrics for 'sans-serif'.  Falling back to 'Times' metrics
Warning: no hard-coded metrics for 'sans-serif'.  Falling back to 'Times' metrics
Warning: no hard-coded metrics for 'sans-serif'.  Falling back to 'Times' metrics
Warning: no hard-coded metrics for 'sans-serif'.  Falling back to 'Times' metrics
Warning: no hard-coded metrics for 'sans-serif'.  Falling back to 'Times' metrics
Warning: no hard-coded metrics for 'sans-serif'.  Falling back to 'Times' metrics
Warning: no hard-coded metrics for 'sans-serif'.  Falling back to 'Times' metrics
```
Last message is repeated 100 more times.

What does this warning mean? It doesn't appear important, so how can I fix it or silence it?

##### **Operating System, Node.js, npm, compodoc version(s)**

$ npm --version
6.14.17
$ node --version
v14.19.2

Compodoc v1.1.19

##### **Angular configuration, a `package.json` file in the root folder**

<details>
  <summary>Angular v11 package.json</summary>

## package.json
```json
{
  "name": "app",
  "version": "4.9.2",
  "private": true,
  "description": "Angular Web Application",
  "license": "UNLICENSED",
  "scripts": {
    "analyze": "ng build --stats-json && npx webpack-bundle-analyzer dist/app/stats-es2015.json",
    "build": "ng build",
    "docs": "npx compodoc --tsconfig tsconfig.json --silent",
    "explore": "ng build && source-map-explorer dist/app/*.js",
    "lint": "ng lint && npm run lint:styles",
    "lint:styles": "stylelint 'src/**/*.{css,scss,sass}' --cache",
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "watch": "ng build --watch --configuration development",
    "writeversion": "node scripts/version.js"
  },
  "dependencies": {
    "@angular/animations": "~12.2.16",
    "@angular/common": "~12.2.16",
    "@angular/compiler": "~12.2.16",
    "@angular/core": "~12.2.16",
    "@angular/fire": "~7.1.1",
    "@angular/forms": "~12.2.16",
    "@angular/localize": "^12.2.16",
    "@angular/platform-browser": "~12.2.16",
    "@angular/platform-browser-dynamic": "~12.2.16",
    "@angular/router": "~12.2.16",
    "@firebase/app-types": "^0.7.0",
    "@formulajs/formulajs": "^3.1.5",
    "@ng-bootstrap/ng-bootstrap": "^10.0.0",
    "@sentry/angular": "^7.8.0",
    "@sentry/integrations": "^7.8.0",
    "@typeform/embed": "^1.36.1",
    "bootstrap": "^4.6.2",
    "canvas-confetti": "^1.5.1",
    "chart.js": "^2.9.4",
    "date-fns": "^2.29.1",
    "firebase": "^9.9.1",
    "hammerjs": "^2.0.8",
    "intersection-observer": "^0.12.2",
    "ng-in-viewport": "^13.0.0",
    "ng2-charts": "^2.4.3",
    "rxfire": "^6.0.0",
    "rxjs": "~6.6.7",
    "smoothscroll-polyfill": "^0.4.4",
    "tslib": "^2.4.0",
    "zone.js": "0.11.6"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^12.1.3",
    "@angular-devkit/build-angular": "^12.2.18",
    "@angular-eslint/builder": "12.7.0",
    "@angular-eslint/eslint-plugin": "12.7.0",
    "@angular-eslint/eslint-plugin-template": "12.7.0",
    "@angular-eslint/schematics": "12.7.0",
    "@angular-eslint/template-parser": "12.7.0",
    "@angular/cli": "^12.2.18",
    "@angular/compiler-cli": "~12.2.16",
    "@angular/language-service": "~12.2.16",
    "@compodoc/compodoc": "^1.1.19",
    "@sentry/cli": "^2.5.0",
    "@sentry/webpack-plugin": "^1.19.0",
    "@types/canvas-confetti": "^1.4.3",
    "@types/hammerjs": "^2.0.41",
    "@types/jasmine": "~3.8.2",
    "@types/node": "^14.18.22",
    "@types/smoothscroll-polyfill": "^0.3.1",
    "@typescript-eslint/eslint-plugin": "4.28.2",
    "@typescript-eslint/parser": "4.28.2",
    "crc": "^4.1.1",
    "eslint": "^7.26.0",
    "eslint-import-resolver-typescript": "^2.7.1",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-rxjs": "^2.1.7",
    "eslint-plugin-rxjs-angular": "^1.0.6",
    "eslint-plugin-tsdoc": "^0.2.16",
    "eslint-plugin-typescript-sort-keys": "^2.1.0",
    "eslint-plugin-unicorn": "^40.1.0",
    "jasmine-core": "~3.8.0",
    "jshint": "^2.13.5",
    "karma": "^6.4.0",
    "karma-chrome-launcher": "^3.1.1",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "^4.0.2",
    "karma-jasmine-html-reporter": "~1.7.0",
    "source-map-explorer": "^2.5.1",
    "stylelint": "^14.9.1",
    "stylelint-config-standard-scss": "^5.0.0",
    "stylelint-csstree-validator": "^2.0.0",
    "stylelint-declaration-block-no-ignored-properties": "^2.5.0",
    "stylelint-high-performance-animation": "^1.6.0",
    "stylelint-no-unsupported-browser-features": "^5.0.3",
    "stylelint-order": "^5.0.0",
    "stylelint-scss": "^4.3.0",
    "stylelint-selector-tag-no-without-class": "^2.0.5",
    "stylelint-use-nesting": "^3.0.0",
    "typescript": "~4.3.5",
    "webpack-bundle-analyzer": "^4.5.0"
  },
  "engines": {
    "node": "14.17.2",
    "npm": "6.14.13"
  }
}
```

</details>
##### **Compodoc installed globally or locally ?**

locally

##### **If possible sourcecode of the file where it breaks**

No idea... we use `sans-serif` as a fallback font-family. No idea why compodoc cares.

##### **If possible your terminal logs before the error**

All the output is above.

##### **Motivation for or Use Case**

Fills my CI logs with messages that don't matter to me. Unless they should?

##### **Reproduce the error**

See above.

##### **Related issues**

I see the message mentioned in #1280 but no one seems to be talking about these specific messages.

##### **Suggest a Fix**

Don't report font warnings? I have no idea what this message is trying to tell me.

**Comment by rgant** [comment] 2022-09-30 15:33
Any idea what this could be?

**Comment by reduckted** [comment] 2023-01-08 06:33
Bump. 

What does this warning even mean? How can we fix it?

**Comment by Sublime1** [comment] 2023-04-18 11:19
This looks like Graphviz issue 2179. They claim to have fixed it but it's still happening in 8.0.3 for me.
https://gitlab.com/graphviz/graphviz/-/issues/2179

**Comment by rgant** [comment] 2023-04-18 13:48
That does look similar, but how does Graphviz and compodoc relate?

**Comment by Sublime1** [comment] 2023-04-18 13:55
> That does look similar, but how does Graphviz and compodoc relate?

Sorry I can't help you there. I just thought I'd point out that the source of the issue is Graphviz.

**Comment by vogloblinsky** [comment] 2023-05-18 06:48
Fixed with https://github.com/compodoc/compodoc/commit/ef9bd945fae4fe27ee0e112ff5a77ce83131b264
Will land in 1.1.20 version this week.

**Closed as completed by vogloblinsky** 2023-05-18 06:48 UTC
Labels: Type: Bug
