### ISSUE TITLE
[BUG] NodeJs Process remains when serving in CLI.

### ISSUE THREAD

**Issue by ste2425** [compodoc/compodoc#564] opened 2018-05-11 13:38 UTC
##### **Overview of the issue**

When running the following command in Git Bash `compodoc -p ./ClientApp/tsconfig.json -s` then pressing `Ctrl` + `c` to terminate, the NodeJs process serving the site remains alive. This means you can still hit `http://localhost:8080` even after the command has been terminated.

This also means when running the command again it throws a warning saying port in use and attempts to find another, on my system it never does anything after that and hangs there.

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10 Enterprise,
NodeJs V6.11.1,
NPM V3.10.10
Compodoc V1.1.2

##### **Angular configuration, a `package.json` file in the root folder**

Reproducible using the compodoc-demo project found [here](https://github.com/compodoc/compodoc-demo-todomvc-angular).

Just need to change the npm doc command to `compodoc -p src/tsconfig.json -s`

##### **Compodoc installed globally or locally ?**

Locally, executed with the following NPM script:
`compodoc -p ./ClientApp/tsconfig.json -s`

##### **Motivation for or Use Case**

It is essentially a memory leak, process being used are not destroyed when the commands are terminated.

##### **Reproduce the error**

Execute the following command in Git Bash
`compodoc -p ./ClientApp/tsconfig.json -s --theme Readthedocs`

Press `Ctrl` + `c` to terminate the command.

Hit `http://localhost:8080` in your browser and it will still be alive.

##### **Related issues**

Nope

##### **Suggest a Fix**

Not too sure, sorry

**Comment by vogloblinsky** [comment] 2018-05-16 13:58
https://github.com/nodejs/node/issues/16103#issuecomment-356922054

Seems to be a bug in Git bash, fixed in Git for Windows 2.15.1.2

https://github.com/nodejs/node/issues/16103#issuecomment-362189516

Could you test it ?

**Comment by jbankester** [comment] 2018-05-17 21:44
I also had this issue previously. I updated to Git for Windows 2.17.0 earlier today and could no longer reproduce.
(Windows 10, Node 9.4.0)

**Comment by ste2425** [comment] 2018-05-18 07:37
Thanks for the update all, yup i upgrade my git for windows to 2.17 and the issue is resolved.

Ill close this, thanks for looking into it.

**Closed** 2018-05-18 07:37 UTC
Labels: 1. Type: Bug, 1. Type: Invalid
