### ISSUE TITLE
[BUG] Error when generating docs (Parse error on line 33, Expecting 'CLOSE', got 'ID')

### ISSUE THREAD

**Issue by dominique-mueller** [compodoc/compodoc#296] opened 2017-09-04 09:24 UTC
##### **Overview of the issue**

When trying to generate the documentation, the following error occurs:

``` bash
[11:17:26] Process page   : typealiases
[11:17:26] Process page   : enumerations
[11:17:26] Process page   : coverage
[11:17:26] Error: Parse error on line 33:
...      {{> menu data menu='normal' }}
-----------------------^
Expecting 'CLOSE', got 'ID'
```

##### **Operating System, Node.js, npm, compodoc version(s)**

- Issue occuring with `compodoc 1.0.0-beta.14` and `compodoc 1.0.0-beta.15`
(`compodoc 1.0.0-beta.13` worked fine although the generation took forever)
- Windows 7
- NodeJS 8.2.1
- Angular 4.3.2

##### **Angular configuration, a `package.json` file in the root folder**

The command we use:
``` bash
compodoc src/lib --tsconfig src/tsconfig.docs.json
```

The referenced tsconfig file:
``` json
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "../out-tsc/app",
    "sourceMap": true,
    "target": "es6",
    "types": []
  },
  "exclude": [
    "test.ts",
    "polyfills.ts",
    "main.ts",
    "index.ts",
    "**/*.spec.ts",
    "app/**/*"
  ]
}
```

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

The documentation won't build at all.

**Comment by wshelley** [comment] 2017-09-19 16:20
I get this bug, but only in my CI environment. Do you have an idea of where the issue is or a workaround?

**Comment by dominique-mueller** [comment] 2017-09-20 08:24
Not a clue, the error message includes a reference to a code line but I have no knowledge of the compodoc internals to figure this out.

**Comment by wshelley** [comment] 2017-09-21 12:30
Its also strange that it only happens in certain environments. It works on my Mac but not within a docker container.

**Comment by dominique-mueller** [comment] 2017-09-21 16:22
Ok, I've just updated to version `1.0.1`, cleaned the node_modules folder and removed the package-lock file to make a clean install - and it works now. No idea what happended, perhaps even an issue within our codebase.

All I remember is that we've removed some circular dependencies recently, perhaps what might have caused the issue. Still weird that you can reproduce the issue ...

**Comment by vogloblinsky** [comment] 2017-10-08 22:02
Closing for cleaning issues. I will re-open it if it comes again.

**Closed by vogloblinsky** 2017-10-08 22:02 UTC
Labels: Priority: Medium, Time: ~1 hour, Type: Bug

**Comment by wshelley** [comment] 2017-10-13 11:15
Still getting this error but only on our build system:
1.0.1
Node.js version : v8.4.0
Operating system : Linux 4.4

Working on my local machine:
1.0.1
Node.js version : v6.11.1
Operating system : macOS Sierra

Maybe a node version issue?

**Comment by wshelley** [comment] 2017-10-13 11:17
[11:07:53] Process page   : variables
[11:07:53] Process page   : enumerations
[11:07:53] Process page   : coverage
[11:07:53] Error: Parse error on line 33:
...      {{> menu data menu='normal' }}   
-----------------------^
Expecting 'CLOSE', got 'ID'

**Comment by wshelley** [comment] 2017-11-09 14:55
reverted to a lower node version and it worked :)

**Comment by vogloblinsky** [comment] 2017-11-10 08:35
@wshelley from which version to which version of node did you manage to solve this issue ?
Thanks

**Comment by wshelley** [comment] 2017-11-10 08:45
It worked on node.js 6.x

I didn't work on 8.9.1 and above. But there could be something in my project causing a conflict.

Anyway I found the docs also stated which versions were supported:
https://compodoc.github.io/website/guides/installation.html

If it is restricted by node version it might be worth putting this in the package.json or README.md
