### ISSUE TITLE
[BUG] Input properties of extended class ignored

### ISSUE THREAD

**Issue by fsz** [compodoc/compodoc#324] opened 2017-10-10 08:08 UTC
##### **Overview of the issue**

A component extends a class that is not a component. The inputs of the extended class are not visible in the output.

```javascript
@Component({ .. })
export class InputTextComponent extends InputBase {
    @Input()
    public value: any;
```

```javascript
export class InputBase {
    public id = index++;

    @Input()
    public label: string;
```

Output:

![image](https://user-images.githubusercontent.com/3602198/31375084-ab47ac2e-ada0-11e7-93a7-eed197fc1796.png)

![image](https://user-images.githubusercontent.com/3602198/31375212-14dd2e2a-ada1-11e7-9ab9-332e2f4bf2ad.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 7
node.js 6.11.2
yarn 1.1.0
compodoc 1.0.1

##### **Motivation for or Use Case**

There is no possibility other than to look into the source to see the inputs of the extended class.
The inputs are not even listed on the class itself - probably because it is no component.

**Comment by vogloblinsky** [comment] 2017-10-29 20:51
Duplicate of https://github.com/compodoc/compodoc/issues/152

**Comment by Chazing** [comment] 2018-02-28 06:50
I need it also,
When component extend base class, we want to see flat list of inputs and outputs, not link to base class.
I would be very grateful if you did this soon
Thanks for  your amazing project!!

**Closed** 2018-03-07 06:59 UTC
Labels: 1. Type: Bug, 1. Type: Duplicate, Priority: Medium, Status: Completed, Time: ~1 hour
