### ISSUE TITLE
[BUG] Private methods and properties are skipped

### ISSUE THREAD

**Issue by MikeSaprykin** [compodoc/compodoc#99] opened 2017-02-03 18:50 UTC
##### **Overview of the bug**
When you mark a property or a method as private - compodoc skips it

##### **Reproduce the error**

Just make a public property, document it and then run compodoc
<img width="807" alt="public-code" src="https://cloud.githubusercontent.com/assets/16716561/22603961/1b85f4c2-ea52-11e6-8f69-cbf017e21708.png">
<img width="637" alt="public" src="https://cloud.githubusercontent.com/assets/16716561/22603962/1b86d5ea-ea52-11e6-8e0c-91923d7c80fb.png">

Then make this property private and run compodoc
<img width="798" alt="private-1" src="https://cloud.githubusercontent.com/assets/16716561/22603960/1b5d5314-ea52-11e6-9f9d-82aadc15a539.png">
<img width="670" alt="private-3" src="https://cloud.githubusercontent.com/assets/16716561/22603963/1b96964c-ea52-11e6-96ca-90e8e58aad4d.png">

Property disappears =)

**Comment by mattlewis92** [comment] 2017-02-04 18:59
This is by design - anything marked as private isn't part of a components public API. If you try and use private methods of a class outside of the class itself the typescript compiler will complain.

**Comment by vogloblinsky** [comment] 2017-02-04 19:09
@mattlewis92 @MikeSaprykin Compodoc will support this in next release by default like Typedoc, but the flag --disablePrivateOrInternalSupport will give the possibility to desactivate it.

**Comment by mattlewis92** [comment] 2017-02-04 19:12
Ah that makes sense 😀

**Closed** 2017-02-06 07:40 UTC
Labels: bug
