### ISSUE TITLE
[BUG] Cannot escape @ signs in markdown code blocks

### ISSUE THREAD

**Issue by krotscheck** [compodoc/compodoc#351] opened 2017-10-31 17:08 UTC
##### **Overview of the issue**

When using markdown code blocks in JS documents, including typescript tags such as `@NgModule` or `@Injectable()` results in broken document rendering. I'm guessing that's because they're interpreted as JSDoc tags.

##### **Operating System, Node.js, npm, compodoc version(s)**

OSX, Node 7.5.0, yarn 1.2.1, compodoc 1.0.2

##### **Angular configuration, a `package.json` file in the root folder**

I don't think this is applicable?

##### **Compodoc installed globally or locally ?**

Both

##### **Motivation for or Use Case**

I would like to have my code samples include copy/pasteable module injection examples.

##### **Reproduce the error**

    /**
     * This is a large comment block with some code samples.
     *
     * ```
     * @NgModule({
     *    imports: [],
     * })
     * export class AppModule {
     * }
     * ```
     *
     * ```typescript
     * @Injectable()
     * export class MyService () {
     * }
     * ```
     */

**Comment by krotscheck** [comment] 2017-10-31 17:10
Note that I've tried a variety of escaping strategies. Ticks, slashes, \u0040, &#040; etc.

**Comment by vogloblinsky** [comment] 2017-10-31 20:56
Duplicate of https://github.com/compodoc/compodoc/issues/304

This can help : https://github.com/compodoc/compodoc/issues/304#issuecomment-336959178

**Closed** 2017-10-31 21:31 UTC
Labels: 1. Type: Duplicate
