### ISSUE TITLE
BUG: COMPODOC_SEARCH_INDEX is not defined

### ISSUE THREAD

**Issue by sosharma1403** [compodoc/compodoc#326] opened 2017-10-11 13:30 UTC
##### **Overview of the issue**
Search functionality does not work if files are not specified in `tsconfig.json` and throws below mentioned error.

Stack trace:
 Uncaught ReferenceError: COMPODOC_SEARCH_INDEX is not defined
    at LunrSearchEngine.init (search-lunr.js:13)
    at Object.<anonymous> (search-lunr.js:59)
    at Object.dispatchEvent (EventDispatcher.js:88)
    at HTMLDocument.<anonymous> (compodoc.js:11)

##### **Operating System, Node.js, npm, compodoc version(s)**

Node.js version : v6.11.1

Operating system : Windows 7

Compodoc version: 1.0.1

##### **Compodoc installed globally or locally ?**
locally

**Comment by vinayakpatil** [comment] 2017-10-11 13:50
+1

**Comment by vogloblinsky** [comment] 2017-10-11 14:09
@sosharma1403 Could you provide a concrete example ?

**Comment by sosharma1403** [comment] 2017-10-12 09:38
This is related to [Bug](https://github.com/compodoc/compodoc/issues/316)

**Comment by vogloblinsky** [comment] 2017-10-12 19:49
@sosharma1403 
Could you describe a little more the context of your issue ?
Did Compodoc breaks ?
What do you mean by "Search functionality does not work if files are not specified in tsconfig.json"

**Comment by sosharma1403** [comment] 2017-10-13 12:45
```javascript
this.connection = window['seamless'] && window['seamless'](this.componentIframe.nativeElement, {
      spinner: 'data:image/gif;base64,R0lGODlhEAAQAJECAAA7/wA6/v///wAAACH/C05FVFNDQVBFMi4wAwEAAAAh/wtYTVAgRGF0YVhNUDw ' // goes on
    });
```

Removing encoded base64 GIF resolves COMPODOC_SEARCH_INDEX error

@vogloblinsky Can you provide a fix for it?

**Comment by vogloblinsky** [comment] 2017-10-13 12:49
Where did you put this code ?
Inside a component ? a class ?

**Comment by sosharma1403** [comment] 2017-10-13 12:51
Inside a Component

**Comment by vogloblinsky** [comment] 2017-10-13 12:51
Can i have all the base64 gif ?

**Comment by sosharma1403** [comment] 2017-10-13 12:53
data:image/gif;base64,R0lGODlhEAAQAJECAAA7/wA6/v///wAAACH/C05FVFNDQVBFMi4wAwEAAAAh/wtYTVAgRGF0YVhNUDw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNi1jMTM4IDc5LjE1OTgyNCwgMjAxNi8wOS8xNC0wMTowOTowMSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo0YWVlNTY4Mi1mMjcwLTQ3MjYtOWI2ZC04NTA5MDc1ZTUzZmYiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MDY4NEIwMjMxRDhEMTFFNzkwQ0VCODA4NkZGRUUzQjYiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MDY4NEIwMjIxRDhEMTFFNzkwQ0VCODA4NkZGRUUzQjYiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTcgKE1hY2ludG9zaCkiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo0YWVlNTY4Mi1mMjcwLTQ3MjYtOWI2ZC04NTA5MDc1ZTUzZmYiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6NGFlZTU2ODItZjI3MC00NzI2LTliNmQtODUwOTA3NWU1M2ZmIi8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+Af/+/fz7+vn49/b19PPy8fDv7u3s6+rp6Ofm5eTj4uHg397d3Nva2djX1tXU09LR0M/OzczLysnIx8bFxMPCwcC/vr28u7q5uLe2tbSzsrGwr66trKuqqainpqWko6KhoJ+enZybmpmYl5aVlJOSkZCPjo2Mi4qJiIeGhYSDgoGAf359fHt6eXh3dnV0c3JxcG9ubWxramloZ2ZlZGNiYWBfXl1cW1pZWFdWVVRTUlFQT05NTEtKSUhHRkVEQ0JBQD8+PTw7Ojk4NzY1NDMyMTAvLi0sKyopKCcmJSQjIiEgHx4dHBsaGRgXFhUUExIREA8ODQwLCgkIBwYFBAMCAQAAIfkECQoAAgAsAAAAABAAEAAAAh+Uj6nL7R1iMHKKWqnU2ObbeRvYcWJJnpjJPu4Lx3ABACH5BAkKAAIALAAAAAAQABAAAAIdlI+piwEQGIJOHgqswVpw/VmhNDLlcioO1LXuqxQAIfkECQoAAgAsAAAAABAAEAAAAiuUj6nLFgCCClSK+GY1GGjKUV5SWd1nimiYkduluiDcIiU7NsIT6f4PZBQAACH5BAkKAAIALAAAAAAQABAAAAIjlI+pyxkfFIxiSmisw5UjrX1ceIBeOZ5Z+lxt9zYwJdf2fRQAIfkECQoAAgAsAAAAABAAEAAAAh+Uj6nL7RliUHKKSqXBUF+PcFzojYcInmXKmM8Lx04BACH5BAUKAAIALAAAAAAQABAAAAIflI+py+0dYjByilqp1Njm23kb2HFiSZ6YyT7uC8dwAQAh+QQFCgACACwAAAAAAQABAAACAlQBACH5BAUKAAIALAAAAAABAAEAAAICVAEAOw==

**Comment by vogloblinsky** [comment] 2017-10-13 13:00
@sosharma1403 Can i have your terminal logs generated by Compodoc ?

**Comment by sosharma1403** [comment] 2017-10-13 13:14
[output.txt](https://github.com/compodoc/compodoc/files/1382684/output.txt)

**Comment by vogloblinsky** [comment] 2017-10-13 13:37
@sosharma1403 
In your logs, it seems you stop the command after `[18:43:30] Process page   : PlayTooltipComponent`, isn't it ?

I cannot reproduce this issue inside my Windows 7 VM, with Node 6.11.1 and compodoc 1.0.1, and your code inside a simple component.

**Comment by vogloblinsky** [comment] 2017-12-12 21:00
Fixed with https://github.com/compodoc/compodoc/commit/f495cd8ab1d2b2a9063db833d2fddf318c0a8d67

**Closed** 2017-12-12 20:59 UTC
Labels: 1. Type: Bug, Priority: Medium, Status: Accepted, Status: Waiting feedback, Time: ~3 hours
