### ISSUE TITLE
[FEATURE] Todo list

### ISSUE THREAD

**Issue by michael-letcher** [compodoc/compodoc#446] opened 2018-01-23 10:08 UTC
##### **Motivation for or Use Case**
Would be nice to have a todo list created via the @todo (or any todo) in comment blocks.
This could give a nice overview of where attention is needed as there would (could) be more todos that needs to be fixed.

**Comment by vogloblinsky** [comment] 2018-01-23 10:09
Duplicate of https://github.com/compodoc/compodoc/issues/383

**Comment by michael-letcher** [comment] 2018-01-23 10:11
@vogloblinsky You can close this ticket due to duplicate

**Closed** 2018-01-23 10:12 UTC
Labels: 1. Type: Duplicate, 1. Type: Enhancement, Status: Accepted
