### ISSUE TITLE
[BUG] @example + `@` within code example (e.g. decorators) is not parsed correctly.

### ISSUE THREAD

**Issue by shlomiassaf** [compodoc/compodoc#270] opened 2017-08-07 22:09 UTC
Including `@` sign within at ` ```typescript ` example is not parsed correctly.

```ts
export class Test {

  /**
   * ```typescript
   * @Component({selector: 'someting'}) export class Sometihng {};
   * ```
  value: string;
}
```

I think the parser does not skip special tokens when they are contained (out of scope)

**Comment by vogloblinsky** [comment] 2017-08-08 13:15
Duplicate of https://github.com/compodoc/compodoc/issues/203

**Closed** 2019-10-07 17:58 UTC
Labels: Context : JSDoc, Priority: Medium, Status: Accepted, Type: Bug, Type: Duplicate, TypeScript issue, wontfix

**Comment by vogloblinsky** [comment] 2021-07-15 10:21
Fixed in 1.1.14
