### ISSUE TITLE
[FEATURE] Is there any way to update favicon.ico while document generation.

### ISSUE THREAD

**Issue by junedansari** [compodoc/compodoc#353] opened 2017-11-01 08:26 UTC
First of all i would like congratulates and thank you guys for such a great document tool .

Need your help and suggestion if there is any way to change favicon.ico while document generation.

Thanks

**Comment by vogloblinsky** [comment] 2017-11-01 09:36
Duplicate of https://github.com/compodoc/compodoc/issues/310

**Closed by vogloblinsky** 2017-11-01 09:36 UTC
Labels: 1. Type: Duplicate, 1. Type: Enhancement, Priority: Medium, Status: Accepted
