### ISSUE TITLE
[BUG] : Dependencies.svg file not generated

### ISSUE THREAD

**Issue by dylabar** [compodoc/compodoc#34] opened 2016-12-12 16:28 UTC
I am currently running into an issue where the **graph/dependencies.svg** file does not appear to be generated. I have performed the following steps:

1. Installed via "npm install --save-dev compodoc".
2. Build and run via an npm script:
`"compodoc": "./node_modules/.bin/compodoc -p tsconfig.json -s --port 8081"`
3. An error is displayed where the graph should be, stating that "Your browser does not support SVG".
4. I manually installed the angular2-dependencies-graph in dev dependencies, this did not help.
5. The following errors are displayed in the developer console of Google Chrome while sitting on the overview page.

> menu.js:31 Uncaught TypeError: Cannot read property 'offsetTop' of null

> svg-pan-zoom.controls.js:1 GET http://127.0.0.1:8081/graph/dependencies.svg 404 (Not Found)

> svg-pan-zoom.min.js:161 Uncaught TypeError: this.options.svg.createSVGMatrix is not a function

It is worth noting that I do not have a README.md file, thus that is skipped during the building of the documents. However, that is the only error I receive during build.

**Comment by vogloblinsky** [comment] 2016-12-12 16:31
What is your environment ?
OS, Node.js, npm, versions
Do you have a screenshot of your console log ?
Are the sources available online ?

**Comment by dylabar** [comment] 2016-12-12 17:17
Environment: Windows 7, npm v3.9.3, compodoc v0.0.21, angular2-dependencies-graph v1.0.0-alpha.12
Console Log Code Dump: 
Source Code: The source code is not available online, as it contains sensitive data. However, it is worth noting that it is a structured project with multiple package.json files. I am using compodoc on a lower level, independent section of the project. The rest of the documents appear to render properly when viewing files independently. (For example, I can view the documentation of my components and see their appropriate properties and functions)

Fantastic work on this project by the way. Even the partial functionality that I currently have is immensely useful, and I appreciate the quick assistance with this.

**Comment by dylabar** [comment] 2016-12-12 18:44
My initial response has been updated with a code dump of the compodoc log. Some information, such as the active Windows user, has been removed.

**Comment by vogloblinsky** [comment] 2016-12-12 20:35
@dylabar 
Could you please edit the node_modules/compodoc/dist/index.js file : 
- around line 549 : 
replace ' -s -t svg' with ' -t svg'
- around line 551 : 
replace silent: true with silent: false
and copy-paste again your console log with just between these 2 lines : 
[11:13:25] Process main graph
...
[11:13:27] Documentation generated in ./documentation/ in 143.276 seconds

**Comment by dylabar** [comment] 2016-12-12 22:06
Sure, here are the results:
https://codedump.io/share/daP9AQBPj5P0/1

I presume the following line relates to the issue at hand.

> no deps      : May be you should consider providing another entry file. See -h

However, I don't see a flag for selecting an entry file.

**Comment by dylabar** [comment] 2016-12-12 22:54
Digging a little further, I notice that this error message is coming from the dependency 'angular2-dependencies-graph', the one I had to manually install. 

What are all of the required dependencies of compodoc? Are they the listed dependencies in this file? https://github.com/compodoc/compodoc/blob/master/package.json

**Comment by vogloblinsky** [comment] 2016-12-13 05:43
Yes, they are all listed in compodoc package.json file and installed with it by npm.

The problem is here : 
"no deps      : May be you should consider providing another entry file. See -h"

angular2-dependencies-graph seems not finding any dependencies from your sources.

Sorry, but without access to your sources for debugging, you have to do it from your side.

Just install angular2-dependencies-graph in your project : npm i --save-dev angular2-dependencies-graph

- edit node_modules/angular2-dependencies-graph/dist/platform/node/compiler/walker.js
- in function "getDependencies", log deps before the last return, and see if it is empty

**Comment by dylabar** [comment] 2016-12-14 19:56
@vogloblinsky 

I've updated the walker.js file as specified, but am not receiving any logs in the browser when serving the compodoc app. Below is my code, should I be looking elsewhere for these logs?

```
Dependencies.prototype.getDependencies = function () {
            var _this = this;
            var deps = [];
            var sourceFiles = this.program.getSourceFiles() || [];
            sourceFiles.map(function (file) {
                var filePath = file.fileName;
                if (path.extname(filePath) === '.ts') {
                    if (filePath.lastIndexOf('.d.ts') === -1 && filePath.lastIndexOf('spec.ts') === -1) {
                        logger_1.logger.info('parsing', filePath);
                        try {
                            _this.getSourceFileDecorators(file, deps);
                        }
                        catch (e) {
                            logger_1.logger.trace(e, file.fileName);
                        }
                    }
                }
		console.log(deps);
                return deps;
            });
	console.log(deps);
        return deps;
        };
```

**Comment by vogloblinsky** [comment] 2016-12-14 21:32
For the debug, just install angular2-dependencies-graph in your project and forgot compodoc.
Run : 
./node_modules/.bin/ngd -p ./tsconfig.json
The supposed console.log('deps: ', deps) should appear during the ngd process.

**Comment by flashdave1973** [comment] 2017-01-02 20:21
Just out of curiosity @vogloblinsky, do you have any spaces in the absolute path to your project folder?

**Comment by vogloblinsky** [comment] 2017-01-02 21:23
@flashdave1973 it could be related to [#44](https://github.com/compodoc/compodoc/issues/44)

**Comment by dylabar** [comment] 2017-01-04 19:35
@vogloblinsky, I performed the logging of dependencies as you suggested, and noticed that no dependencies were being used.

In attempting to solve this, I went to the NPM page for [angular-2-depencies-graph](https://www.npmjs.com/package/angular2-dependencies-graph), manually installed the listed dependencies, and re-compiled. However, there are still no dependencies listed. Any suggestions?

**Comment by vogloblinsky** [comment] 2017-01-04 19:55
> Manually installed the listed dependencies ?

What do you mean ?
Try installing ngd globally : ```npm i -g angular2-dependencies-graph```
and run ngd on your project : 
```ngd -p ./tsconfig.json```

**Comment by dylabar** [comment] 2017-01-04 20:01
I installed ngd globally and ran it on my project, and received the same error:

> no deps : May be you should consider providing another entry file. See -h

Here is my entry file, tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node"
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```

**Comment by vogloblinsky** [comment] 2017-01-04 20:03
What are the console logs of ngd ?
```Including : xxx```
```Ignoring : xxx```

**Comment by dylabar** [comment] 2017-01-04 20:08
The includes are a list of what appears to be all the *.ts files in my app. The ignored files are any *.ts files in the typings folder as specified by tsconfig. As far as I can tell, this is working as expected.

Would you still like a censored code dump of the output?

**Comment by vogloblinsky** [comment] 2017-01-27 05:24
@dylabar 
Yes why not.
Did you retry with last version of compodoc ? 0.0.37

**Comment by vogloblinsky** [comment] 2017-02-18 00:39
Closing, last version use ngd directly without CLI call as before. Give it a try ;)

**Closed by vogloblinsky** 2017-02-18 00:39 UTC
Labels: bug
