### ISSUE TITLE
[BUG] @example + Angular decorator goes wrong

### ISSUE THREAD

**Issue by Chazing** [compodoc/compodoc#584] opened 2018-06-12 06:30 UTC
##### **Overview of the issue**

When i wrote comment on  class, and in the code there is '@', the code black window not appear in the compodoc generated documentation, and the comment cut off/

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc version: 1.1.3

##### **Compodoc installed globally or locally ?**

locally

##### **Reproduce the error**

Write this code on class

\/**
  \* Usage example
  \* \```typescript
  \* export class FormExampleComponent {
 \* @ViewChild("pnl", { read: ViewContainerRef }) pnl: ViewContainerRef;
  \* constructor() { }
\*}
  \* \```
  \* \```html
  \* <div #pnl>
  \* </div>
  \* \```
 */
@Injectable()
export class SomeService {
...
  }
 run compodoc, and then you can see that the documentation not generated correctly.

Thanks

**Comment by vogloblinsky** [comment] 2018-06-12 07:12
Duplicate of #203

**Comment by vogloblinsky** [comment] 2018-12-06 03:43
Duplicate of #270

**Closed** 2019-10-07 17:58 UTC
Labels: Context : JSDoc, Priority: Medium, Status: Accepted, Time: ~1 hour, Type: Bug, Type: Duplicate, wontfix
