### ISSUE TITLE
[FEATURE] Miscellaneous items are not available in search

### ISSUE THREAD

**Issue by alan-agius4** [compodoc/compodoc#447] opened 2018-01-24 08:06 UTC
##### **Overview of the issue**

I have several ` Miscellaneous` items such as `Functions`, `Enums` and when I search they are not clearly visible.

##### **Motivation for or Use Case**
I would expect that these are visible similar to `Interfaces`, `Classes` etc... in search and not just like the below;

![image](https://user-images.githubusercontent.com/17563226/35320966-f96bb39e-00e5-11e8-91eb-adef533912fc.png)

**Comment by vogloblinsky** [comment] 2018-02-12 06:08
Search engine is powered by https://lunrjs.com/
During documentation generation, all pages are indexed with it.
As each items of Miscellaneous sections are grouped by types, it will be difficult to do a better job as today. 
I just can try to find a better way to display search results.

**Comment by alan-agius4** [comment] 2018-02-14 09:33
I see, thanks

**Comment by vogloblinsky** [comment] 2018-04-20 06:28
Duplicate of https://github.com/compodoc/compodoc/issues/537

**Closed** 2018-04-22 03:35 UTC
Labels: 1. Type: Enhancement, Context : search, Priority: Medium, Status: Accepted, Time: ~3 hours
