### ISSUE TITLE
[FEATURE] option to provide configurations as JSON

### ISSUE THREAD

**Issue by Sibiraj-S** [compodoc/compodoc#426] opened 2018-01-02 11:29 UTC
Options can be passed either as flags or as a JSON in package.json.

for example
``` json
"name": "@my/foo",
"version": "1.0.0",
"dependencies": {},
"compodoc": {
    "name": "Angular",
    "disableGraph": true
}
```

or could be a seperate file
```json
{
  "start": " ",
   "doc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json --options compodoc.json"
}
```

compodoc.json
```json
{
    "name": "Angular",
    "disableGraph": true
}
```

**Comment by vogloblinsky** [comment] 2018-01-11 02:18
Duplicate of https://github.com/compodoc/compodoc/issues/379

**Closed by vogloblinsky** 2018-01-11 02:18 UTC
