### ISSUE TITLE
[BUG] Support for multiple Items with the same name

### ISSUE THREAD

**Issue by markwpearce** [compodoc/compodoc#474] opened 2018-02-15 18:29 UTC
##### **Overview of the issue**

If I have two items (e.g. modules, interfaces, etc) with the same name, the documentation does not show both.

For example, if we have two files:

*auth.ts*:

``` typescript
export interface State {
 loggedIn: boolean;
 userId: string;
}
```

*products.ts*:
``` typescript
export interface State {
 [id:string]:string
}
```

Compodoc only produces one /interfaces/State.html route, so only one of these items is documented.

##### **Motivation for or Use Case**

Using nx (https://github.com/nrwl/nx), and we have multiple apps, so there are multiple app.module.ts

Also using ngrx, so we define a lot of "State" interfaces, and import things like: 

``` typescript
import * as fromAuth from 'auth-lib'; //exports interface State
import * as fromProducts from 'products-lib'; //exports interface State

const interface appState {
  auth: fromAuth.State,
  products: fromProducts.State
}
```

##### **Suggest a Fix**

Add extra data to the processing and routing in the documentation to give unique ids to each module, component, interface, class, etc.

Don't match on name (eg. in Application.prepareModules) - https://github.com/compodoc/compodoc/blob/develop/src/app/application.ts#L621) match instead on this unique id

**Comment by vogloblinsky** [comment] 2018-02-15 19:52
Duplicate of https://github.com/compodoc/compodoc/issues/145

**Closed** 2018-03-26 10:57 UTC
Labels: 1. Type: Duplicate, 1. Type: Enhancement, Priority: Medium, Time: ~3 hours
