### ISSUE TITLE
[FEATURE] Allow  specific modifiers (like disablePrivateOrInternalSupport)

### ISSUE THREAD

**Issue by shlomiassaf** [compodoc/compodoc#271] opened 2017-08-08 11:04 UTC
Currently, the only option to control the output based on modifiers is `--disablePrivateOrInternalSupport`

This option is generic and combines modifiers (private) with tags (`@internal`).

I would like to suggest to remove it and replace it with:

### `@internal`
For `@internal` support there is no need  for a flag, as it can be inferred from `tsconfig` ** stripInternal** option. As a backup a flag can be added but I think using `tsconfig` should work fine.

### modifiers
For modifiers a flag with a list of comma separated modifiers can be set that allows fine grained control. While `private` is the most common modifier to remove in some cases `protected` might also be a candidate, for example in a library I build I would like to create documentation for consumers that is simple, protected members clutter the code and I would like to omit them, a developer API documentation might later add them.

Not directly related to the topic but as this library move forward using just CLI tags will get messy and a config file is required

**Comment by vogloblinsky** [comment] 2017-08-11 01:40
Duplicate of https://github.com/compodoc/compodoc/issues/241
Using a config file was in my todo list since the beginning of this project. I will try to implement that soon.
The original idea was to extend original tsconfig.json file.
Right now i think i will :
- split --disablePrivateOrInternalSupport
- provide flags : --disablePrivate , --disableProtected, --disableInternal
- don't konw if static and inherited need flags ?

**Comment by vogloblinsky** [comment] 2017-11-08 23:50
Available In 1.0.4

**Closed by vogloblinsky** 2017-11-08 23:50 UTC
Labels: 1. Type: Enhancement, Priority: Medium, Status: Completed, Time: ~3 hours
