### ISSUE TITLE
[FEATURE] --disableTemplate flag to disable the Template tab

### ISSUE THREAD

**Issue by bparkhurst** [compodoc/compodoc#553] opened 2018-05-02 17:48 UTC
##### **Overview of the issue**

We would like to disable the Template tab because it really does not mean anything to our end users.  It actually confuses them because we are building a framework that they use.  The template is our source so it has nothing to do with what they need.

##### **Motivation for or Use Case**

To make things more consistent for our end users and not show something that confuses them.

**Comment by Blakesalot** [comment] 2018-05-03 17:25
It seems like this may be a duplicate of #545

**Comment by vogloblinsky** [comment] 2018-05-06 07:11
Close this, duplicate.

**Closed by vogloblinsky** 2018-05-06 07:11 UTC
Labels: 1. Type: Duplicate, 1. Type: Enhancement, 1. Type: Invalid

**Comment by bparkhurst** [comment] 2018-05-07 16:09
Hi there!  How is 1.1.3 coming along with the searching fixed?  We are releasing our product in about 3 weeks.

Brett

**Comment by vogloblinsky** [comment] 2018-05-08 06:09
hi brett,
This week. Last issues for 1.1.3 milestone are here : https://github.com/compodoc/compodoc/milestone/21

**Comment by bparkhurst** [comment] 2018-05-14 12:36
That is so great!  I really appreciate your follow-up and work on this Vincent.  This is just in time for our release!

We will continue to help donate to your product.

Brett

**Comment by bparkhurst** [comment] 2018-05-16 14:51
Hi Vincent!

I hope you are doing well.  We are two days away from cutting our beta version.  Do you think we can run a test on 1.1.3 today or tomorrow?

Thanks!

Brett
